### ISSUE TITLE
arg_parse.c: Support multiple files conversion

### ISSUE THREAD

**Issue by Karatuss** [danny-burrows/img_to_txt#1]
Hi, @danny-burrows.
This issue is for `arg_parse.c` file.

## About suggestion

When I used the program, I ran the command below.

 > ./img_to_txt -hw 100 01.jpg -hw 50 02.jpg

As you can guess, I just wanted to convert multiple files with different options separately.
But, the results generated by the program showed me that they have same spec (or scale) given by the very last option (in this case, `-hw 50`).

So, there is my suggestion I want you to consider.
**Could I make a pull request about dealing with multiple files that have different options?**

### Expected changes

- Delete a `--` detecting condition
- Reorganization the structure of `arg_parse` function

This is just a draft, so you don't have to take care of them deeply.

---
Thanks for reading, and I look forward to hearing from you.

**Comment by danny-burrows** [comment]
Hello @TwoPair, I'd be more than open to accepting a pull request to fix this behavior. The original usage was modeled on a review of the common utility `ls` but I can absolutely see that having the option for different settings for each image would be of benefit.

Thank you for your interest and contribution, I look forward to hearing more on this. :)
