### ISSUE TITLE
header files - #ifndef macro names

### ISSUE THREAD

**Issue by Karatuss** [danny-burrows/img_to_txt#3]
Good day, @danny-burrows.

Don't you think that header's macro name is little long?
Now - `#ifndef IMG_TO_TXT_ARG_H`
In my opinion, `IMG_TO_TXT_` part is not necessary and is difficult to classify headers.

So how about this format?
Suggestion - `#ifndef ARG_H`
In more detail, if a header named 'hello.h' is located in `include/here`, just express like this - `#ifndef HERE_HELLO_H`.

If you have any other idea, please let me hear your feedback.

**Comment by danny-burrows** [comment]
Hey @TwoPair, thanks again for the issue! I'd be willing to consider this change, I think I see what you mean with `IMG_TO_TXT_` being confusing if we are following the convention for guards that you mentioned. 

The only concern I had when authoring this is I wanted to be 100% sure that the guards cannot be defined anywhere else to avoid horrible include errors.

That being said I think you've made a solid point and I would be willing to accept a PR with this change. All the best. :)
